owner: robingenz
repo: upptime

sites:
  - name: robingenz.dev
    url: https://robingenz.dev/
  - name: NC
    url: $NC_URL
  - name: TS3 Server
    url: $TS3_URL
  - name: IA
    url: $IA_URL
  - name: HN
    url: $HN_URL
  - name: DHBW VS Internal API
    url: $DHBW_VS_INTERNAL_API_URL
    headers:
      - "Authorization: Bearer $DHBW_VS_INTERNAL_API_AUTH_TOKEN"
      - "Content-Type: application/x-www-form-urlencoded"
    expectedStatusCodes:
      - 200
  - name: DHBW VS External API
    url: $DHBW_VS_EXTERNAL_API_URL
    expectedStatusCodes:
      - 404
  - name: KickerTracker App
    url: $KICKERTRACKER_APP_URL
  - name: KickerTracker API
    url: $KICKERTRACKER_API_URL
    expectedStatusCodes:
      - 404

assignees:
  - robingenz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
