owner: robingenz
repo: upptime

sites:
  - name: robingenz.dev
    url: https://robingenz.dev/
  - name: NC
    url: $NC_URL
  - name: TS3 Server
    url: $TS3_URL
  - name: IA
    url: $IA_URL
  - name: HN
    url: $HN_URL

assignees:
  - robingenz

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
